apiVersion: v1
kind: pod
metadata:
  name: mutli-containers
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]

# kind: Pod
# apiVersion: v1
# metadata:
#   name: multi-container
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#   - name: almalinux
#     image: almalinux:9
#     command: ["sleep","1000"]     

