kind: Service
apiVersion: v1
metadate:
 name: nginx
spec:
 selector:
   project: expense
   module: backend
   environment: dev
Ports:
- name: nginx-Svc-Ports
  protocal: TCP
  port: 80
  targetport: 80  
