kind: Pod
apiVersion: v1
metadata:
 name: limits
spec:
 containers:
 - name: nginx
   image: nginx
   resources:
     requests:
       cpu: 100m
       memory: 68Mi
     limit: 
       cpu: 120m
       memory: 100Mi